language: php

php:
    - 5.3
    - 5.4
    - 5.5

cache:
    composer: true
    directories:
        - vendor

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar --prefer-source --dev install

script: 
    - phpunit --coverage-clover clover

notifications:
    email:
        - leve42.dev@gmail.com